### PR TITLE
added CONTRIBUTING.md file

### LINKED ISSUE #10: Create Contribution.md

### PR DESCRIPTION
**Pull request by NotAtitYet**
Please review and merge my PR

### CODE REVIEW

**Comment by NotAtitYet** [comment]
#10

**Comment by kramerbastian** [comment]
Amazing! Just replace the word website in the feature section with tool 😉

**Comment by NotAtitYet** [comment]
> Amazing! Just replace the word website in the feature section with tool 😉

Ok

**Comment by kramerbastian** [comment]
Great

**Pull request merged**
